{% set name = "mms-python-client" %}
{% set version = "3.4.2.1" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6855d99218ed7e219e37d6cb6628443ac3abeb1921c16e0f778b1aee3e625290

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - urllib3 >=1.15
    - six >=1.10
    - certifi
    - python-dateutil

test:
  imports:
    - mms_python_client

about:
  home: http://openmbee.org
  license: Apache 2.0
  license_file: LICENSE
  summary: Model Management Service
  description: 'Model Management System (MMS) is a version control system for structured data. It exposes model information through RESTful web services that can be used for CRUD operations, branching,
    and tagging of the model repository.'

extra:
  recipe-maintainers: 
    - HuiJun
