{% set name = "mms-python-client" %}
{% set version = "4.0.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4556b7d25e4a3ea9284bd0780f5b7691d7e547cb34851aaebf3decc1b91721b9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - urllib3 >=1.15
    - six >=1.10
    - certifi
    - python-dateutil

test:
  imports:
    - mms_python_client

about:
  home: http://openmbee.org
  license: Apache-2.0
  license_file: LICENSE
  summary: Model Management Service
  description: Model Management System (MMS) is a version control system for structured data. It exposes model information through RESTful web services that can be used for CRUD operations, branching, and tagging of the model repository.

extra:
  recipe-maintainers:
    - HuiJun
    - dlamoris
